### PR TITLE
Adjust example for new info gain output. #64

### LINKED ISSUE #64: cutOff_k description
cutOff_k example is still based on rownames.

### PR DESCRIPTION
**Pull request by krzyslom**
This resolves #64 issue.

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
Why there is a need for an output of class list? Have you add such a notę to the 'NEWS.md'? Do examples in vignettes also need an update/ And then also our website (stored in the 'docs' directory)?

**Comment by krzyslom** [comment]
@MarcinKosinski I do not quite get your comment in context of this issue. ```information_gain``` returns attributes' names as a column, not as rownames. Hence change in the example – ```x[[1]]``` instead of ```rownames(x)```. It is a description for hidden cpp function. I did it only for consistency.

**Comment by zzawadz** [comment]
It might be better to have attributes names as column, not rownames. It make FSelectorRcpp more pipe friendly.
@krzyslom can you add NEWS.md entry about that change?

**Comment by MarcinKosinski** [comment]
@krzyslom so update NEWS and then this can be merged?

**Pull request merged**
